/**
 * Golf Empire's Top 100 England (golfempire.reviews/magazine-lists/top-100-england),
 * captured 2026-08-18. One of three ranking sources feeding the Vestige Index
 * `ranking` axis.
 *
 * Stored as a typed constant (same pattern as `curated-import/top100-england.ts`)
 * so the import is reproducible, diffable in git when the list is republished,
 * and needs no live scrape at runtime.
 */

import type { ImportInputRow } from "@/lib/curated-import/match";

export const GOLF_EMPIRE_ENGLAND: ImportInputRow[] = [
  { rank: 1, name: "Royal St. George's Golf Club", location: null },
  { rank: 2, name: "Sunningdale Golf Club (Old)", location: null },
  { rank: 3, name: "Sunningdale Golf Club (New)", location: null },
  { rank: 4, name: "Swinley Forest Golf Club", location: null },
  { rank: 5, name: "Royal Lytham & St. Annes Golf Club", location: null },
  { rank: 6, name: "St. Enodoc Golf Club (Church)", location: null },
  { rank: 7, name: "Ganton Golf Club", location: null },
  { rank: 8, name: "Royal Birkdale Golf Club", location: null },
  { rank: 9, name: "St. George's Hill Golf Club (Red & Blue)", location: null },
  { rank: 10, name: "Royal Cinque Ports Golf Club", location: null },
  { rank: 11, name: "West Sussex (Pulborough) Golf Club", location: null },
  { rank: 12, name: "Rye Golf Club (Old)", location: null },
  { rank: 13, name: "Woodhall Spa Golf Club (Hotchkin)", location: null },
  { rank: 14, name: "Walton Heath Golf Club (Old)", location: null },
  { rank: 15, name: "Royal West Norfolk (Brancaster) Golf Club", location: null },
  { rank: 16, name: "Royal Liverpool (Hoylake) Golf Club", location: null },
  { rank: 17, name: "Alwoodley Golf Club", location: null },
  { rank: 18, name: "Notts (Hollinwell) Golf Club", location: null },
  { rank: 19, name: "Silloth on Solway Golf Club", location: null },
  { rank: 20, name: "The Berkshire Golf Club (Red)", location: null },
  { rank: 21, name: "Hillside Golf Club", location: null },
  { rank: 22, name: "Formby Golf Club", location: null },
  { rank: 23, name: "Saunton Golf Club (East)", location: null },
  { rank: 24, name: "Wentworth Golf Club (West)", location: null },
  { rank: 25, name: "Hankley Common Golf Club", location: null },
  { rank: 26, name: "Burnham & Berrow (Championship)", location: null },
  { rank: 27, name: "Woking Golf Club", location: null },
  { rank: 28, name: "Queenwood Golf Club", location: null },
  { rank: 29, name: "Hunstanton Golf Club", location: null },
  { rank: 30, name: "Liphook Golf Club", location: null },
  { rank: 31, name: "Worplesdon Golf Club", location: null },
  { rank: 32, name: "West Hill Golf Club", location: null },
  { rank: 33, name: "Parkstone Golf Club", location: null },
  { rank: 34, name: "The Berkshire Golf Club (Blue)", location: null },
  { rank: 35, name: "West Lancashire Golf Club", location: null },
  { rank: 36, name: "Prince's Golf Club (Shore & Dunes)", location: null },
  { rank: 37, name: "The Addington Golf Club", location: null },
  { rank: 38, name: "Broadstone Golf Club", location: null },
  { rank: 39, name: "JCB Golf & Country Club", location: null },
  { rank: 40, name: "Hindhead Golf Club", location: null },
  { rank: 41, name: "Walton Heath Golf Club (New)", location: null },
  { rank: 42, name: "Delamere Forest Golf Club", location: null },
  { rank: 43, name: "Southport & Ainsdale Golf Club", location: null },
  { rank: 44, name: "Wallasey Golf Club", location: null },
  { rank: 45, name: "New Zealand Golf Club", location: null },
  { rank: 46, name: "Moortown Golf Club", location: null },
  { rank: 47, name: "Ipswich Golf Club", location: null },
  { rank: 48, name: "Royal Ashdown Forest Golf Club (Old)", location: null },
  { rank: 49, name: "Beau Desert Golf Club", location: null },
  { rank: 50, name: "Wentworth Golf Club (East)", location: null },
  { rank: 51, name: "Aldeburgh Golf Club", location: null },
  { rank: 52, name: "Sherwood Forest Golf Club", location: null },
  { rank: 53, name: "Ferndown Golf Club (Old)", location: null },
  { rank: 54, name: "Woburn Golf Club (Marquess)", location: null },
  { rank: 55, name: "Hayling Golf Club", location: null },
  { rank: 56, name: "Saunton Golf Club (West)", location: null },
  { rank: 57, name: "Woburn Golf Club (Duke's)", location: null },
  { rank: 58, name: "Bearwood Lakes Golf Club", location: null },
  { rank: 59, name: "Stoneham Golf Club", location: null },
  { rank: 60, name: "Little Aston Golf Club", location: null },
  { rank: 61, name: "Remedy Oak Golf Club", location: null },
  { rank: 62, name: "Coombe Hill Golf Club", location: null },
  { rank: 63, name: "Royal North Devon Golf Club", location: null },
  { rank: 64, name: "Blackmoor Golf Club", location: null },
  { rank: 65, name: "Huntercombe Golf Club", location: null },
  { rank: 66, name: "Littlestone Golf Club", location: null },
  { rank: 67, name: "Seaton Carew Golf Club", location: null },
  { rank: 68, name: "Perranporth Golf Club", location: null },
  { rank: 69, name: "Trevose Golf Club (Championship)", location: null },
  { rank: 70, name: "The Wisley Golf Club", location: null },
  { rank: 71, name: "Seacroft Golf Club", location: null },
  { rank: 72, name: "Lindrick Golf Club", location: null },
  { rank: 73, name: "East Devon Golf Club", location: null },
  { rank: 74, name: "Royal Wimbledon Golf Club", location: null },
  { rank: 75, name: "Berwick upon Tweed Golf Club (Goswick)", location: null },
  { rank: 76, name: "Tandridge Golf Club", location: null },
  { rank: 77, name: "Hadley Wood Golf Club", location: null },
  { rank: 78, name: "Blackwell Golf Club", location: null },
  { rank: 79, name: "Camberley Heath Golf Club", location: null },
  { rank: 80, name: "Ashridge Golf Club", location: null },
  { rank: 81, name: "North Hants Golf Club", location: null },
  { rank: 82, name: "The Grove Golf Club", location: null },
  { rank: 83, name: "Sutton Coldfield Golf Club", location: null },
  { rank: 84, name: "Woburn Golf Club (Duchess')", location: null },
  { rank: 85, name: "St. Mellion Golf Club", location: null },
  { rank: 86, name: "Stoke Park Golf Club (Colt & Alison)", location: null },
  { rank: 87, name: "Royal Worlington & Newmarket Golf Club", location: null },
  { rank: 88, name: "Knole Park Golf Club", location: null },
  { rank: 89, name: "Sheringham Golf Club", location: null },
  { rank: 90, name: "Isle of Purbeck Golf Club", location: null },
  { rank: 91, name: "Woodbridge Golf Club", location: null },
  { rank: 92, name: "Prestbury Golf Club", location: null },
  { rank: 93, name: "Cavendish Golf Club", location: null },
  { rank: 94, name: "Crowborough Beacon Golf Club", location: null },
  { rank: 95, name: "Kington Golf Club", location: null },
  { rank: 96, name: "Northamptonshire County Golf Club", location: null },
  { rank: 97, name: "Cleeve Hill Golf Club", location: null },
  { rank: 98, name: "Yelverton Golf Club", location: null },
  { rank: 99, name: "Thorndon Park Golf Club", location: null },
  { rank: 100, name: "Coxmoor Golf Club", location: null },
];
