/**
 * Today's Golfer's Top 200 England (todays-golfer.com/courses/best/golf-courses-in-england),
 * captured 2026-08-18. The deepest of the three ranking sources - it reaches 200
 * where the others stop at 100, so it is the only source covering the 100-200 band.
 *
 * Names are stored exactly as published (upper-case, curly apostrophes); the
 * matcher lower-cases and strips punctuation, so no normalisation is needed here.
 */

import type { ImportInputRow } from "@/lib/curated-import/match";

export const TODAYS_GOLFER_ENGLAND: ImportInputRow[] = [
  { rank: 1, name: "ROYAL ST GEORGE’S", location: null },
  { rank: 2, name: "SUNNINGDALE (OLD)", location: null },
  { rank: 3, name: "ROYAL BIRKDALE", location: null },
  { rank: 4, name: "SUNNINGDALE (NEW)", location: null },
  { rank: 5, name: "WOODHALL SPA (HOTCHKIN)", location: null },
  { rank: 6, name: "SWINLEY FOREST", location: null },
  { rank: 7, name: "ROYAL LIVERPOOL", location: null },
  { rank: 8, name: "ROYAL CINQUE PORTS", location: null },
  { rank: 9, name: "ST GEORGE’S HILL", location: null },
  { rank: 10, name: "ROYAL LYTHAM & ST ANNES", location: null },
  { rank: 11, name: "WALTON HEATH (OLD)", location: null },
  { rank: 12, name: "ALWOODLEY", location: null },
  { rank: 13, name: "GANTON", location: null },
  { rank: 14, name: "ST ENODOC (CHURCH)", location: null },
  { rank: 15, name: "RYE", location: null },
  { rank: 16, name: "FORMBY", location: null },
  { rank: 17, name: "ROYAL WEST NORFOLK", location: null },
  { rank: 18, name: "WOKING", location: null },
  { rank: 19, name: "WEST SUSSEX", location: null },
  { rank: 20, name: "SILLOTH-ON-SOLWAY", location: null },
  { rank: 21, name: "SAUNTON EAST", location: null },
  { rank: 22, name: "HANKLEY COMMON", location: null },
  { rank: 23, name: "BURNHAM & BERROW", location: null },
  { rank: 24, name: "HOLLINWELL", location: null },
  { rank: 25, name: "THE BERKSHIRE (RED)", location: null },
  { rank: 26, name: "HILLSIDE", location: null },
  { rank: 27, name: "HUNSTANTON", location: null },
  { rank: 28, name: "PRINCE’S", location: null },
  { rank: 29, name: "WEST LANCS", location: null },
  { rank: 30, name: "WENTWORTH (WEST)", location: null },
  { rank: 31, name: "THE ADDINGTON", location: null },
  { rank: 32, name: "WORPLESDON", location: null },
  { rank: 33, name: "MOORTOWN", location: null },
  { rank: 34, name: "PARKSTONE", location: null },
  { rank: 35, name: "WEST HILL", location: null },
  { rank: 36, name: "BROADSTONE", location: null },
  { rank: 37, name: "LIPHOOK", location: null },
  { rank: 38, name: "WALLASEY", location: null },
  { rank: 39, name: "THE JCB CLUB", location: null },
  { rank: 40, name: "THE BERKSHIRE (BLUE)", location: null },
  { rank: 41, name: "WALTON HEATH (NEW)", location: null },
  { rank: 42, name: "SOUTHPORT & AINSDALE", location: null },
  { rank: 43, name: "ROYAL ASHDOWN FOREST (OLD)", location: null },
  { rank: 44, name: "HINDHEAD", location: null },
  { rank: 45, name: "SHERWOOD FOREST", location: null },
  { rank: 46, name: "HAYLING", location: null },
  { rank: 47, name: "ROYAL WORLINGTON & NEWMARKET", location: null },
  { rank: 48, name: "ROYAL NORTH DEVON", location: null },
  { rank: 49, name: "WOBURN (MARQUESS)", location: null },
  { rank: 50, name: "ALDEBURGH", location: null },
  { rank: 51, name: "BEAU DESERT", location: null },
  { rank: 52, name: "FERNDOWN", location: null },
  { rank: 53, name: "SEACROFT", location: null },
  { rank: 54, name: "NEW ZEALAND", location: null },
  { rank: 55, name: "WENTWORTH (EAST)", location: null },
  { rank: 56, name: "GOSWICK", location: null },
  { rank: 57, name: "TREVOSE", location: null },
  { rank: 58, name: "SEATON CAREW (MICKLEM)", location: null },
  { rank: 59, name: "HUNTERCOMBE", location: null },
  { rank: 60, name: "DELAMERE FOREST", location: null },
  { rank: 61, name: "IPSWICH (PURDIS HEATH)", location: null },
  { rank: 62, name: "LITTLE ASTON", location: null },
  { rank: 63, name: "TANDRIDGE", location: null },
  { rank: 64, name: "KINGTON", location: null },
  { rank: 65, name: "LITTLESTONE", location: null },
  { rank: 66, name: "EAST DEVON", location: null },
  { rank: 67, name: "THE GROVE", location: null },
  { rank: 68, name: "WOBURN (DUKE’S)", location: null },
  { rank: 69, name: "BLACKMOOR", location: null },
  { rank: 70, name: "SAUNTON (WEST)", location: null },
  { rank: 71, name: "CAVENDISH", location: null },
  { rank: 72, name: "BLACKWELL", location: null },
  { rank: 73, name: "PERRANPORTH", location: null },
  { rank: 74, name: "STONEHAM", location: null },
  { rank: 75, name: "CAMBERLEY HEATH", location: null },
  { rank: 76, name: "KNOLE PARK", location: null },
  { rank: 77, name: "PILTDOWN", location: null },
  { rank: 78, name: "CLEEVE HILL", location: null },
  { rank: 79, name: "WOODBRIDGE", location: null },
  { rank: 80, name: "BEARWOOD LAKES", location: null },
  { rank: 81, name: "WOBURN (DUCHESS)", location: null },
  { rank: 82, name: "LINDRICK", location: null },
  { rank: 83, name: "HADLEY WOOD", location: null },
  { rank: 84, name: "ISLE OF PURBECK", location: null },
  { rank: 85, name: "FORMBY LADIES", location: null },
  { rank: 86, name: "SEASCALE", location: null },
  { rank: 87, name: "ASHRIDGE", location: null },
  { rank: 88, name: "PRESTBURY", location: null },
  { rank: 89, name: "SHERINGHAM", location: null },
  { rank: 90, name: "COOMBE HILL", location: null },
  { rank: 91, name: "BERKHAMSTED", location: null },
  { rank: 92, name: "SUTTON COLDFIELD", location: null },
  { rank: 93, name: "NORTHANTS COUNTY", location: null },
  { rank: 94, name: "CROWBOROUGH BEACON", location: null },
  { rank: 95, name: "ST ANNES OLD LINKS", location: null },
  { rank: 96, name: "NORTH HANTS", location: null },
  { rank: 97, name: "THORPENESS", location: null },
  { rank: 98, name: "REMEDY OAK", location: null },
  { rank: 99, name: "ROYAL WIMBLEDON", location: null },
  { rank: 100, name: "CHART HILLS", location: null },
  { rank: 101, name: "FULFORD", location: null },
  { rank: 102, name: "THE WISLEY (CHURCH & MILL)", location: null },
  { rank: 103, name: "EFFINGHAM", location: null },
  { rank: 104, name: "THE BELFRY (BRABAZON)", location: null },
  { rank: 105, name: "YELVERTON", location: null },
  { rank: 106, name: "CENTURION CLUB", location: null },
  { rank: 107, name: "ENVILLE (HIGHGATE)", location: null },
  { rank: 108, name: "FOXHILLS (LONGCROSS)", location: null },
  { rank: 109, name: "LUFFENHAM HEATH", location: null },
  { rank: 110, name: "PAINSWICK", location: null },
  { rank: 111, name: "CLEVELAND", location: null },
  { rank: 112, name: "ST MELLION (NICKLAUS)", location: null },
  { rank: 113, name: "THE HALLAMSHIRE", location: null },
  { rank: 114, name: "DUNSTANBURGH CASTLE", location: null },
  { rank: 115, name: "ENVILLE (LODGE)", location: null },
  { rank: 116, name: "BUDE & NORTH", location: null },
  { rank: 117, name: "TADMARTON HEATH", location: null },
  { rank: 118, name: "ROYAL NORWICH", location: null },
  { rank: 119, name: "APPLEBY", location: null },
  { rank: 120, name: "COXMOOR", location: null },
  { rank: 121, name: "COPT HEATH", location: null },
  { rank: 122, name: "ROYAL CROMER", location: null },
  { rank: 123, name: "LONDON CLUB (HERITAGE)", location: null },
  { rank: 124, name: "FRILFORD HEATH (RED)", location: null },
  { rank: 125, name: "MOOR PARK (HIGH) Park", location: null },
  { rank: 126, name: "CLOSE HOUSE (COLT)", location: null },
  { rank: 127, name: "THETFORD", location: null },
  { rank: 128, name: "SANDIWAY", location: null },
  { rank: 129, name: "THORNDON PARK", location: null },
  { rank: 130, name: "BAMBURGH CASTLE", location: null },
  { rank: 131, name: "FAIRHAVEN", location: null },
  { rank: 132, name: "WEST CORNWALL", location: null },
  { rank: 133, name: "TEIGNMOUTH", location: null },
  { rank: 134, name: "WESTON-SUPER-MARE", location: null },
  { rank: 135, name: "KING’S LYNN", location: null },
  { rank: 136, name: "NEWQUAY", location: null },
  { rank: 137, name: "WEST BYFLEET", location: null },
  { rank: 138, name: "GOODWOOD (DOWNS)", location: null },
  { rank: 139, name: "WEST SURREY", location: null },
  { rank: 140, name: "STOCKPORT", location: null },
  { rank: 141, name: "MANCHESTER", location: null },
  { rank: 142, name: "REIGATE HEATH", location: null },
  { rank: 143, name: "BRAMPTON", location: null },
  { rank: 144, name: "LONDON CLUB (INTERNATIONAL)", location: null },
  { rank: 145, name: "CHURCH STRETTON", location: null },
  { rank: 146, name: "HALIFAX", location: null },
  { rank: 147, name: "BURHILL (OLD)", location: null },
  { rank: 148, name: "BEACONSFIELD", location: null },
  { rank: 149, name: "BROKENHURST MANOR", location: null },
  { rank: 150, name: "WILDERNESSE", location: null },
  { rank: 151, name: "ESSENDON (OLD)", location: null },
  { rank: 152, name: "NORTHUMBERLAND", location: null },
  { rank: 153, name: "FRILFORD HEATH (BLUE)", location: null },
  { rank: 154, name: "REDDISH VALE", location: null },
  { rank: 155, name: "HUDDERSFIELD", location: null },
  { rank: 156, name: "MULLION", location: null },
  { rank: 157, name: "FOXHILLS (BERNARD HUNT)", location: null },
  { rank: 158, name: "MINCHINHAMPTON (OLD)", location: null },
  { rank: 159, name: "BINGLEY ST IVES", location: null },
  { rank: 160, name: "WORKSOP", location: null },
  { rank: 161, name: "SAND MOOR", location: null },
  { rank: 162, name: "HOCKLEY", location: null },
  { rank: 163, name: "SLALEY HALL (HUNTING)", location: null },
  { rank: 164, name: "THE BUCKINGHAMSHIRE", location: null },
  { rank: 165, name: "PLEASINGTON", location: null },
  { rank: 166, name: "EAST SUSSEX NATIONAL (WEST)", location: null },
  { rank: 167, name: "RAC (OLD)", location: null },
  { rank: 168, name: "WENTWORTH (EDINBURGH)", location: null },
  { rank: 169, name: "LECKFORD (OLD)", location: null },
  { rank: 170, name: "EDGBASTON", location: null },
  { rank: 171, name: "PANNAL", location: null },
  { rank: 172, name: "BOVEY CASTLE", location: null },
  { rank: 173, name: "ROYAL MID-SURREY (JH TAYLOR)", location: null },
  { rank: 174, name: "ROSS-ON-WYE", location: null },
  { rank: 175, name: "WINDERMERE", location: null },
  { rank: 176, name: "WHITTINGTON HEATH", location: null },
  { rank: 177, name: "ROCKLIFFE HALL", location: null },
  { rank: 178, name: "CARLISLE", location: null },
  { rank: 179, name: "GREAT YARMOUTH & CAISTER", location: null },
  { rank: 180, name: "BRANCEPETH CASTLE", location: null },
  { rank: 181, name: "MANNINGS HEATH (WATERFALL)", location: null },
  { rank: 182, name: "HARTLEPOOL", location: null },
  { rank: 183, name: "CANTERBURY", location: null },
  { rank: 184, name: "YORK", location: null },
  { rank: 185, name: "WILMSLOW", location: null },
  { rank: 186, name: "EAST SUSSEX NATIONAL (EAST)", location: null },
  { rank: 187, name: "ILKLEY", location: null },
  { rank: 188, name: "HEADINGLEY", location: null },
  { rank: 189, name: "SUNNINGDALE HEATH", location: null },
  { rank: 190, name: "SANDWELL PARK", location: null },
  { rank: 191, name: "FARNHAM", location: null },
  { rank: 192, name: "HANBURY MANOR", location: null },
  { rank: 193, name: "EAST BERKSHIRE", location: null },
  { rank: 194, name: "FELIXSTOWE FERRY (MARTELLO)", location: null },
  { rank: 195, name: "THE PLAYERS (STRANAHAN)", location: null },
  { rank: 196, name: "GOG MAGOG (THE OLD)", location: null },
  { rank: 197, name: "FLEMPTON", location: null },
  { rank: 198, name: "ORMSKIRK", location: null },
  { rank: 199, name: "THE CAVERSHAM", location: null },
  { rank: 200, name: "DENHAM", location: null },
];
